### ISSUE TITLE
Question about using mosaic scenario-convert.jar file for xx.net.xml — xx.db

### ISSUE THREAD

**Issue by Jonyian** [eclipse/mosaic#324]
* [ ] **I have checked that this bug has not yet been reported by someone else.**

## Description
When I am using my own map instead of the map sourced from osm for mosaic conversion, there will be a situation where using mosaic's scenario-convert.jar to convert xx.net.xml to xx.db cannot recognize the vehicle road, and then cannot Generate mosaic folder from .db file

## Steps to reproduce

java -jar scenario-convert.jar --sumo2db -i jinfeng6.net.xml
13:58:14.107 INFO  - initializing database
13:58:14.108 INFO  - loading database...
13:58:14.293 INFO  - success

13:58:14.294 INFO  - parsing net file
13:58:14.299 ERROR |- An unexpected error occurred.
java.lang.IllegalStateException: Only UTM projection is supported yet
        at com.dcaiti.mosaic.tools.scenarioconvert.importer.sumo.b.a(Unknown Source)
        at com.dcaiti.mosaic.tools.scenarioconvert.importer.sumo.b.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:276)
        at com.dcaiti.mosaic.tools.scenarioconvert.importer.sumo.b.a(Unknown Source)
        at com.dcaiti.mosaic.tools.scenarioconvert.importer.sumo.a.a(Unknown Source)
        at com.dcaiti.mosaic.tools.scenarioconvert.core.a.a(Unknown Source)
        at com.dcaiti.mosaic.tools.scenarioconvert.core.Starter.main(Unknown Source)
13:58:14.301 ERROR |- Could not load network data from Net File.
java.lang.IllegalStateException: Could not parse network file
        at com.dcaiti.mosaic.tools.scenarioconvert.importer.sumo.b.a(Unknown Source)
        at com.dcaiti.mosaic.tools.scenarioconvert.importer.sumo.a.a(Unknown Source)
        at com.dcaiti.mosaic.tools.scenarioconvert.core.a.a(Unknown Source)
        at com.dcaiti.mosaic.tools.scenarioconvert.core.Starter.main(Unknown Source)
Caused by: java.lang.IllegalStateException: Only UTM projection is supported yet
        at com.dcaiti.mosaic.tools.scenarioconvert.importer.sumo.b.a(Unknown Source)
        at com.dcaiti.mosaic.tools.scenarioconvert.importer.sumo.b.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:276)
        ... 4 common frames omitted
13:58:14.301 INFO  - no route file for import given, ignoring!
13:58:16.142 INFO  - Saving 0 nodes...
13:58:16.143 INFO  - Saving 0 ways...
13:58:16.144 INFO  - Saving 0 connections...
13:58:16.144 INFO  - Saving 0 restrictions...
13:58:16.144 INFO  - Saving 0 routes...
13:58:16.144 INFO  - Saving 0 roundabouts...
13:58:16.144 INFO  - Saving 0 buildings...
13:58:16.145 INFO  - Create Indices
13:58:16.326 INFO  - Database saved
13:58:16.326 INFO  - finished

## Workaround

I suspect it may be <location netOffset="681.36,415.46" convBoundary="0.00,0.00,1359.63,838.78" origBoundary="0.000000,0.000000,0.000000,0.000000" projParameter="+proj=t in my .net.xml file merc +lat_0=29.51771557134214 +lon_0=106.3252472463716 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +geoidgrids=egm96_15.gtx +vunits=m +no_defs "/> projParameter="+ proj=tmerc +lat_0=29.51771557134214 +lon_0=106.3252472463716 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +geoidgrids=egm96_15.gtx +vunits=m +no_defs "/> from osm The converted .net.xml file is different, and the one converted in osm is similar to: projParameter="+proj=utm +zone=48 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"/> So I try Modify the .net.xml. After that, it can be converted to a .db file normally, but there may be some problems with the coordinate deflection, which will affect the subsequent work. At present, I have found that some files in the generated mosaic folder are blank (for example, the scenario_config.json file, so that Unable to proceed to the next step)

## Affected modules

Eclipse MOSAIC Configuration Files
## System information

* **Eclipse MOSAIC version:** eclipse-mosaic-23.0
* **Operating System:** Windows11
* **JDK version/vendor:**  17.06
* **SUMO version:**  1.14.1

**Comment by kschrab** [comment]
Hi, I'm currently trying out things to make the import work with other projections than utm. Can you share your `jinfeng6.net.xml` so I can test scenario-convert with this?

**Comment by kschrab** [comment]
With scenario-convert 23.1 we included [locationtech/proj4j](https://github.com/locationtech/proj4j) to parse the projection description from the `net.xml`. Still, support for the `geoidgrids` parameter is not available and must be removed manually from the descriptor. This issue is therefore resolved.
